services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      APP_ENV: demo
